In [26]:
import pandas as pd

In [27]:
ages = pd.Series([22, 21, 23])
print(ages)

0    22
1    21
2    23
dtype: int64

In [28]:
students = pd.Series(
    [22, 21, 23],
    index = ["Raj", "Aman", "Priya"]
)
print(students)

Raj      22
Aman     21
Priya    23
dtype: int64

In [29]:
students_df = pd.DataFrame(
    {
        "Name":["Raj", "Aman", "Priya"],
        "Age": [22, 21, 23],
        "CGPA": [6.22, 7.8, 8.9]
    }
)

In [30]:
students_df.head()

    Name  Age  CGPA
0    Raj   22  6.22
1   Aman   21  7.80
2  Priya   23  8.90

In [31]:
students_df.tail()

    Name  Age  CGPA
0    Raj   22  6.22
1   Aman   21  7.80
2  Priya   23  8.90

In [32]:
students_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      int64
 2   CGPA    3 non-null      float64
dtypes: float64(1), int64(1), str(1)
memory usage: 204.0 bytes

In [33]:
students_df.describe()

        Age      CGPA
count   3.0  3.000000
mean   22.0  7.640000
std     1.0  1.347145
min    21.0  6.220000
25%    21.5  7.010000
50%    22.0  7.800000
75%    22.5  8.350000
max    23.0  8.900000

In [34]:
students_df.shape

(3, 3)

In [35]:
students_df.columns

Index(['Name', 'Age', 'CGPA'], dtype='str')

In [36]:
students_df.index

RangeIndex(start=0, stop=3, step=1)

In [37]:
df = pd.DataFrame(
    {
        "Name": ["Raj", "Aman", "Priya"],
        "Age": [22, 21, 23],
        "CGPA": [6.22, 7.8, 8.9],
        "weight": [55, 60, 58],
        "college": ["ABC", "XYZ", "PQR"],
        "skills": ["Python", "Java", "C++"]
    }
)

In [38]:
print(df.shape)
print(df.columns)
print(df.index)
print("#########")
print(df.info())
print("#########")
print(df.describe())

(3, 6)
Index(['Name', 'Age', 'CGPA', 'weight', 'college', 'skills'], dtype='str')
RangeIndex(start=0, stop=3, step=1)
#########
<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     3 non-null      str
 1   Age      3 non-null      int64
 2   CGPA     3 non-null      float64
 3   weight   3 non-null      int64
 4   college  3 non-null      str
 5   skills   3 non-null      str
dtypes: float64(1), int64(2), str(3)
memory usage: 276.0 bytes
None
#########
        Age      CGPA     weight
count   3.0  3.000000   3.000000
mean   22.0  7.640000  57.666667
std     1.0  1.347145   2.516611
min    21.0  6.220000  55.000000
25%    21.5  7.010000  56.500000
50%    22.0  7.800000  58.000000
75%    22.5  8.350000  59.000000
max    23.0  8.900000  60.000000

In [39]:
series = pd.Series(
    ["python", "SQL", "Git", "FastAPI", "Docker"],
    index = ["Raj", "Aman", "Priya", "Ravi", "Ramesh"]
)

In [40]:
"""
What is Pandas?
Pandas is a python library that isuased for data manipulation and analysis.

Difference between Series and DataFrame
Series is a one dimensional array which is  used for storing data of any type whereas DataFrame is a 2 dimensional array which is used for storing data of any type in tabular form.

Why is Pandas used?
Pandas is used for data transformaton, cleaning, analysis and visualization.

Difference between Shape and columns?
Shape is used to get the dimensions of the dataframe whereas columns are used to get the name of the columns.

Whaat does info() return?
info() returns the summary if  the dataframe like non null values count, datatypes and memory usage.

What does describe() return?
describe is used to get the mean max median and other statistical information of the dataframe."""

'\nWhat is Pandas?\nPandas is a python library that isuased for data manipulation and analysis.\n\nDifference between Series and DataFrame\nSeries is a one dimensional array which is  used for storing data of any type whereas DataFrame is a 2 dimensional array which is used for storing data of any type in tabular form.\n\nWhy is Pandas used?\nPandas is used for data transformaton, cleaning, analysis and visualization.\n\nDifference between Shape and columns?\nShape is used to get the dimensions of the dataframe whereas columns are used to get the name of the columns.\n\nWhaat does info() return?\ninfo() returns the summary if  the dataframe like non null values count, datatypes and memory usage.\n\nWhat does describe() return?\ndescribe is used to get the mean max median and other statistical information of the dataframe.'

In [41]:
"""Interview Questions
Difference between NumPy and Pandas?
What is a DataFrame?
What is a Series?
Why do we use indexes?
Difference between head() and tail()?"""

'Interview Questions\nDifference between NumPy and Pandas?\nWhat is a DataFrame?\nWhat is a Series?\nWhy do we use indexes?\nDifference between head() and tail()?'

In [ ]:
"""
Quick Revision

- Pandas is used for data manipulation and analysis.
- Series is a one-dimensional labeled data structure.
- DataFrame is a two-dimensional labeled data structure.
- head() shows the first rows.
- tail() shows the last rows.
- shape returns (rows, columns).
- columns returns column names.
- index returns row labels.
- info() gives a summary of the DataFrame.
- describe() returns descriptive statistics.
"""