In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("students.csv")
print(df)

    Name  Age  CGPA Branch
0    Raj   22  6.22     IT
1   Aman   21  7.80    CSE
2  Priya   23  8.90     IT
3   Ravi   22  7.10    CSE

In [3]:
print(df.head())
print(df.tail())
print(df.info())
print(df.describe())
print(df.shape)
print(df.columns)
print(df.dtypes)
print(df.iloc[0:3])
print(df.iloc[-2:])
print(df["Name"])
print(df["CGPA"])
print(df[["Name", "Branch"]])

    Name  Age  CGPA Branch
0    Raj   22  6.22     IT
1   Aman   21  7.80    CSE
2  Priya   23  8.90     IT
3   Ravi   22  7.10    CSE
    Name  Age  CGPA Branch
0    Raj   22  6.22     IT
1   Aman   21  7.80    CSE
2  Priya   23  8.90     IT
3   Ravi   22  7.10    CSE
<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Age     4 non-null      int64
 2   CGPA    4 non-null      float64
 3   Branch  4 non-null      str
dtypes: float64(1), int64(1), str(2)
memory usage: 260.0 bytes
None
             Age      CGPA
count   4.000000  4.000000
mean   22.000000  7.505000
std     0.816497  1.132593
min    21.000000  6.220000
25%    21.750000  6.880000
50%    22.000000  7.450000
75%    22.250000  8.075000
max    23.000000  8.900000
(4, 4)
Index(['Name', 'Age', 'CGPA', 'Branch'], dtype='str')
Name          str
Age         int64
CGPA      float64
Branch        str
dtype: object
    Name  Age  CGPA Branch
0    Raj   22  6.22     IT
1   Aman   21  7.80    CSE
2  Priya   23  8.90     IT
    Name  Age  CGPA Branch
2  Priya   23   8.9     IT
3   Ravi   22   7.1    CSE
0      Raj
1     Aman
2    Priya
3     Ravi
Name: Name, dtype: str
0    6.22
1    7.80
2    8.90
3    7.10
Name: CGPA, dtype: float64
    Name Branch
0    Raj     IT
1   Aman    CSE
2  Priya     IT
3   Ravi    CSE

In [4]:
df["Name"]
df[["Name", "CGPA"]]
"""Why are double brackets needed for multiple columns?
df is a dataframe so to address its two different columns like a matrix double brackets are required"""

'Why are double brackets needed for multiple columns?\ndf is a dataframe so to address its two different columns like a matrix double brackets are required'

In [5]:
print(df.iloc[0])
df.iloc[0:3]
print(df.iloc[0])
print(df.iloc[2])
print(df.iloc[0:2])
print(df.iloc[0:2, 0:3])

Name       Raj
Age         22
CGPA      6.22
Branch      IT
Name: 0, dtype: object
Name       Raj
Age         22
CGPA      6.22
Branch      IT
Name: 0, dtype: object
Name      Priya
Age          23
CGPA        8.9
Branch       IT
Name: 2, dtype: object
   Name  Age  CGPA Branch
0   Raj   22  6.22     IT
1  Aman   21  7.80    CSE
   Name  Age  CGPA
0   Raj   22  6.22
1  Aman   21  7.80

In [14]:
df.loc[0]
df = df.set_index("Name")
df.loc["Raj"]
df.loc["Priya"]
df.loc[["Raj", "Aman"]]
df.loc["Raj", "CGPA"]

np.float64(6.22)

In [ ]:
df.iloc[0:2, 1:3]

      CGPA Branch
Name
Raj   6.22     IT
Aman  7.80    CSE

In [ ]:
df.loc["Raj":"Priya", ["Age", "CGPA"]]

       Age  CGPA
Name
Raj     22  6.22
Aman    21  7.80
Priya   23  8.90

In [ ]:
"""
Difference between CSV and Excel.
CSV is more common because it is lightweight, plain text, faster to read, platform-independent, and easier to process in ML pipelines.
Excel files contain formatting, formulas, and multiple sheets, which are usually unnecessary for machine learning.

Difference between loc and iloc.
loc is to get data from dataframes by the means of labels whereas iloc is to data by the means of position.

Why does iloc not accept labels?
iloc is position based so labels are not acceptable

Difference between selecting one column and multiple columns.
Single brackets select one column and return a Series. Double brackets pass a list of column names and therefore return a DataFrame.
Why do we inspect a dataset before cleaning it?
we inspect a dataset before cleaning to see the info present and what we are dealing with like the no  of columns its data types
 and other statistical info
"""

'\nDifference between CSV and Excel.\ncsv is comma seperated values whereas excel is a ms office formatted tabular data.\n\nDifference between loc and iloc.\nloc is to get data from dataframes by the means of labels whereas iloc is to data by the means of position.\n\nWhy does iloc not accept labels?\niloc is position based so labels are not acceptable\n\nDifference between selecting one column and multiple columns.\nselecting one column gives a series whereas selecting multiple columns gives a dataframe\n\nWhy do we inspect a dataset before cleaning it?\nwe inspect a dataset before cleaning to see the info present and what we are dealing with like the no  of columns its data types\n and other statistical info\n'

In [10]:
df = pd.DataFrame(
    {
        "Name": ["Raj", "Aman", "Priya"],
        "CGPA": [6.22, 7.8, 8.9]
    }
)

In [ ]:
df["CGPA"]
#returns a a series

0    6.22
1    7.80
2    8.90
Name: CGPA, dtype: float64

In [ ]:
df[["CGPA"]]
#returns a dataframe

   CGPA
0  6.22
1  7.80
2  8.90

In [13]:
"""
pandas provide both the series dtype and dataframe dtype so that if we want to make changes toa series or dataframe we have  both the tools"""

'\npandas provide both the series dtype and dataframe dtype so that if we want to make changes toa series or dataframe we have  both the tools'

In [ ]:
"""
Which is the most important inspection function before  cleaning?
df.info()
Because before cleaning, I want to know:

Missing values
Data types
Number of non-null values

describe() is more useful after you understand the structure.
"""